### ISSUE TITLE
'Recipient "" has too many recent signup requests' error

### ISSUE THREAD

**Issue by EmilyNL** [kraftbj/genesis-enews-extended#125]
<img width="623" alt="screen shot 2016-09-27 at 10 05 52" src="https://cloud.githubusercontent.com/assets/22460953/18855923/0732be9c-849a-11e6-96fd-93bde924c149.png">

Anyone know how to fix this? 

Thanks.

**Comment by marckrejci** [comment]
I'm getting this too... :(

**Comment by vierkantemeter** [comment]
Did you ever find a solution or a cause for this problem? I'm getting it too.

**Comment by kraftbj** [comment]
My guess would be that the e-mail form field value is incorrect or something to that effect.

**Comment by daveschappell** [comment]
I just had the same error.  It was only happening on iPhones.  I double-checked that I had the correct info in the Form field.  I was able to fix the error by disabling the 'Recaptcha' option on the Mailchimp signup-form-page.  So... that leaves me at risk to spam signups, right?  But it fixes it.  Hoping that you come up with a solution that allows me to turn the Recaptcha requirement back on.

**Comment by vierkantemeter** [comment]
After some investigation we've tracked down the issue is not at Mailchimp's side, but some code in the form that makes iOS10 iPhones show the _'Recipient "" has too many recent signup requests'_ error.

We're almost there, but as we don't have a iOS10 device to test with (we asked friends) so it's hard to test for us.

We came to the conclusion that:

- This form triggers the error on iOS10 devices: http://van-vlerken.nl/form-en/form3en.html

- This form works good, and doesn't triggers the error: http://van-vlerken.nl/form-en/form4en.html

So, some HTML code in the last form triggers the error. But we're unable to test any further. Can someone else test this, and maybe alter the HTML code to see what exactly triggers the error?

Note; the form only does a post to the result page which show a `print_r($_POST)`. No information is send to me, mailchimp or anyone else.

I've also posted this issue on stackoverflow: http://stackoverflow.com/questions/40914117/mailchimp-embed-form-too-many-recent-signup-requests-on-ios-10-devices

**Comment by kraftbj** [comment]
Thanks for the links. I'll see if I can duplicate the error in iOS 10 and go backwards from there. I'll let you know if I find anything.

**Comment by deinBaum** [comment]
I had this problem (on our website build with webflow) for some weeks now, but not only on iPhones, on Desktop Safari & Chrome too. 

I checked your other post on stackoverflow and tried to add "http:" before the "//". I can't believe it's that easy, but this works for me!

**Comment by JohnCrch** [comment]
Was having this issue in a local test environment using the FireFox browser.
I added EMAIL in the E-Mail Field just under the Form Action and it worked...

**Comment by daveschappell** [comment]
Brandon -- are John & deinBaum's recommendations the final fix?  or are you still researching?

**Comment by vierkantemeter** [comment]
We've finally found the fix. Remove target="_blank" from the <form> tag.

**Comment by thehungryhutch** [comment]
I've removed target="_blank" from the php file, but I'm still getting this error.

[class-bjgk-genesis-enews-extended.txt](https://github.com/kraftbj/genesis-enews-extended/files/815001/class-bjgk-genesis-enews-extended.txt)

**Comment by paulmaunders** [comment]
We have also been getting the 'recipient has too many recent signup requests' error using MailChimp's widget on a completely different project. 

I read a couple of posts about it [here](https://brianhogg.com/avoid-mailchimp-too-many-attempts-signup-error/), [here](https://wordpress.org/support/topic/recreated-recipient-has-too-many-recent-signup-requests-error/) and [here](https://medium.com/@CodingJoe/what-to-do-when-youve-accidentally-become-a-celebrity-and-you-get-this-mailchimp-error-recipient-98b1f0bbbe0c#.1i2gsi41o) as well as this github thread and as a result I tried:

1. Removing the anti-bot hidden div
2. Updating the action url to be specifically https:// instead of just //
3. Disabling the re-captcha option in MailChimp
4. Removing target=_blank from the form tag.
5. Removing **novalidate** from the form tag, and adding **required** to the input tag

Steps 4 or 5 both seemed to fix it for me, but 5 displayed the submission page slightly better.

**Comment by JamieRohrbaugh** [comment]
I am having the same issue with eNews Extended and MailChimp on 3 different sites. I'm trying to fix it per the instructions above, but am not sure where to find the form tag (in order to make the changes recommended above) since the form action is the only thing in eNews Extended. Help? Thanks!

**Comment by digitalmaster** [comment]
@paulmaunders I think step #2 worked for me.. Thanks champ 👍

**Comment by kraftbj** [comment]
I haven't heard of any new issues with this, so I'm going to presume an iOS update helped? I'm going to close it for now, but if y'all are still seeing issues, please comment.

**Comment by zschuessler** [comment]
I was getting this error when the email field was disabled. Removing the disabled attribute allowed the form to work again.

This issue is a top hit in Google, hopefully it helps someone else!

**Comment by mrcoles** [comment]
I also got this error when my form was using "email" instead of the expected uppercase format of "EMAIL".
