### ISSUE TITLE
Aweber issues - names not showing on Aweber list, but appear in email salutation...

### ISSUE THREAD

**Issue by SharonHerrman** [kraftbj/genesis-enews-extended#135]
I'm sure this is really simple, but I can't find anyone to help...Aweber can't.  I have the form set up for First name, Last name, Email...the Aweber list shows the email, but says the names are unknown.  However...when I do test subscribes, the name does appear in the salutation of the email.  Annoying.  Can this be fixed?  Thanks!

**Comment by kraftbj** [comment]
I'm afraid I'm not really of help either. eNews is just the form itself, so if the various field names match -- first name matches what they expect for first name, e-mail for e-mail, etc, it should work the same as aweber.

My best suggestion would be to confirm that those settings are correct for the name fields (by grabbing a copy of their embed code and comparing the two), but otherwise, this plugin doesn't actually handle any data--just the display of the form.
